Estudiantes/urls.py
from django.conf.urls import url

from . import views

app_name = 'Estudiantes'

urlpatterns = [
    #administrador/estudiantes
    url(r'^$', views.student_lists, name='student_lists'),

    # administrador/estudiantes/3/delete
    url(r'^(?P<pk>[0-9]+)/eliminar/$', views.student_delete, name='student_delete'),

    # administrador/estudiantes/3/cambio_status
    url(r'^(?P<pk>[0-9]+)/cambio_status/$', views.student_change_status, name='student_change_status'),

    # administrador/estudiantes/crear/
    url(r'^crear/$', views.student_create, name='student_create'),

    #administrador/estudiantes_editar/3
    url(r'^_editar/(?P<pk>[0-9]+)/', views.student_update.as_view(), name='student_update'),
]

Index/urls.py
from django.conf.urls import url, include
from Usuarios import urls
from . import views

app_name = 'Index'

urlpatterns = [

    #/administrador/
    url(r'^$', views.Index, name='dashboard'),

]

Serendipia/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^administrador', include('Index.urls', namespace='administrador')),
    url(r'^admin/', admin.site.urls),
    url(r'^administrador/inst', include('Instituciones.urls', namespace='instituciones')),
    url(r'^administrador/ssinst', include('SSInstituciones.urls', namespace='ssinstituciones')),
]

Estudiantes/models.py
from django.db import models

# Create your models here.
class Estudiantes(models.Model):

    EstudianteID = models.IntegerField(
        primary_key=True,
        null=False,

    )

    Nombre = models.CharField(
        max_length =50,
        null=False,
    )

    aPaterno = models.CharField(
        max_length=30,
        null=False,
    )
    aMaterno = models.CharField(
        max_length=30,
        null=False,
    )
    Telefono = models.CharField(
        max_length=15,
        null=False,
    )
    Escuela = models.CharField(
        max_length=50,
        null=False,
    )
    Correo = models.EmailField(
        null=False,
    )
    Passwd = models.CharField(
        max_length=20,
        null=False,
    )
    Activo = models.BooleanField(
        default = True,
    )

    def __str__(self):
        return self.Nombre +' '+ self.aPaterno +' '+ self.aMaterno

Estudiantes/forms.py
from .models import Estudiantes
from django import forms


class EstudiantesForm(forms.ModelForm):
    class Meta:
        model = Estudiantes
        fields = ('Nombre', 'aPaterno', 'aMaterno', 'Telefono','Escuela', 'Correo','Passwd' )

Estudiantes/views.py
from django.shortcuts import render
from django.views.generic import UpdateView
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse, reverse_lazy

from .models import Estudiantes

from .forms import EstudiantesForm


# Create your views here.


def student_lists(request):
    all_students = Estudiantes.objects.all()
    context ={
        'all_students': all_students
        }
    return render(request, 'Estudiantes/student_list.html',context)

def student_create(request):
    context = {}
    NewEstudiantesForm = EstudiantesForm()

    # if this is a POST request we need to process the form data
    if request.method == 'POST':

        # create a form instance and populate it with data from the request
        NewEstudiantesForm = EstudiantesForm(request.POST)
        StudentValid = NewEstudiantesForm.is_valid()

        # check whether it's valid
        if StudentValid:
            Est = NewEstudiantesForm.save(commit=False)
            Est.Activo = True
            ID = Estudiantes.objects.count() + 1
            Est.EstudianteID = ID
            Est.save()
            return student_lists(request)

    context = {
        'NewEstudiantesForm': NewEstudiantesForm
    }
    return render(request, 'Estudiantes/student_form.html', context)

    # if a GET (or any other method) we'll create a blank form
    return render(request, 'Estudiantes/student_form.html', context)

class student_update(UpdateView):
    model = Estudiantes
    fields = [
        'Nombre',
        'aPaterno',
        'aMaterno',
        'Telefono',
        'Escuela',
        'Correo',
        'Passwd'
    ]
    template_name = 'Estudiantes/student_edit_form.html'

    success_url = reverse_lazy('Estudiantes:student_lists')

def student_delete(request, pk):
    student = Estudiantes.objects.filter(pk=pk)
    student.delete()
    return HttpResponseRedirect(reverse('Estudiantes:student_lists'))

def student_change_status(request, pk):
    student = Estudiantes.objects.get(pk=pk)
    if student.Activo:
        student.Activo = False
        student.save()
    else:
        student.Activo = True
        student.save()
    return HttpResponseRedirect(reverse('Estudiantes:student_lists'))

Estudiantes/templates/Estudiantes/student_edit_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container">
    <br>
    <h3 class="center green-text text-accent-2"> Estudiantes - Editar Estudiante </h3>
    <br> <br> <br>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <button type="submit" class="waves-light btn green accent-2">Confimar Estudiante</button>
    </form>
</div>

{% endblock content %}

Estudiantes/templates/Estudiantes/student_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container">
    <br>
    <h3 class="center green-text text-accent-2"> Estudiantes - Crear Estudiantes </h3>
    <br> <br> <br>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <div class="row">
                <label for="Nombre"> Nombre: </label>
                {{ NewEstudiantesForm.Nombre | add_class:'form-control' }}
            </div>
            <div class="row">
                <label for="aPaterno"> Apellido Paterno: </label>
                {{ NewEstudiantesForm.aPaterno | add_class:'form-control' }}
            </div>
            <div class="row">
                <label for="aMaterno"> Apellido Materno: </label>
                {{ NewEstudiantesForm.aMaterno | add_class:'form-control' }}
            </div>
            <div class="row">
                <label for="Telefono"> Telefono: </label>
                {{ NewEstudiantesForm.Telefono | add_class:'form-control' }}
            </div>
            <div class="row">
                <label for="Escuela"> Escuela: </label>
                {{ NewEstudiantesForm.Escuela | add_class:'form-control' }}
            </div>
            <div class="row">
                <label for="Correo"> Correo: </label>
                {{ NewEstudiantesForm.Correo | add_class:'form-control' }}
            </div>
            <div class="row">
                <label for="Passwd"> Contrasenia: </label>
                {{ NewEstudiantesForm.Passwd | add_class:'form-control' }}
            </div>
        </div>
        <button type="submit" class="waves-light btn green accent-2">Agregar Estudiante</button>
    </form>
</div>

{% endblock content %}

Estudiantes/templates/Estudiantes/student_list.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

    <div class="container">
        <br>
        <h3 class="center green-text text-accent-2"> Estudiantes </h3>
        <br> <br> <br>
        <a href="{% url 'Estudiantes:student_create' %}" class="waves-light btn green accent-2"><i class="material-icons right">add</i>Agregar Estudiante</a>
        <br> <br> <br> <br>
        <table class="highlight responsive-table">
            <thead class="thead-default">
                <tr>
                    <th class="center-align">Nombre</th>
                    <th class="center-align">Apellidos</th>
                    <th class="center-align">Telefono</th>
                    <th class="center-align">Escuela</th>
                    <th class="center-align">Correo</th>
                    <th class="center-align">Activo</th>
                </tr>
            </thead>
            <tbody>
            {% for student in all_students %}

            <tr>
                <td class="center-align">{{student.Nombre}}</td>
                <td class="center-align">{{student.aPaterno}}</td>
                <td class="center-align">{{student.aMaterno}}</td>
                <td class="center-align">{{student.Telefono}}</td>
                <td class="center-align">{{student.Escuela}}</td>
                <td class="center-align">{{student.Correo}}</td>

                <td class="center-align">
                    <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Editar Estudiante"
                       href="{% url 'Estudiantes:student_update' student.pk %}">
                        <i class="material-icons light-blue-text">create</i>
                    </a>&nbsp; &nbsp; &nbsp; &nbsp;
                    <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Eliminar Estudiante"
                       href="{% url 'Estudiantes:student_delete' student.pk %}">
                        <i class="material-icons red-text">delete</i>
                    </a> &nbsp; &nbsp; &nbsp; &nbsp;
                    <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Cambiar Estatus"
                       href="{% url 'Estudiantes:student_change_status' student.pk %}">
                    <i class="material-icons blue-grey-text">compare_arrows</i>
                    </a>
                </td>

                {% if student.Activo == True %}
                <td class="center-align"><i class="material-icons green-text">done</i></td>
                {% else %}
                <td class="center-align"><i class="material-icons red-text">clear</i></td>
                {% endif %}
            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>



{% endblock content %}