Index/urls.py
from django.conf.urls import url, include
from Usuarios import urls
from . import views

app_name = 'Index'

urlpatterns = [

    #/administrador/
    url(r'^$', views.Index, name='dashboard'),

]

Instituciones/urls.py
from django.conf.urls import url

from . import views

app_name = 'Instituciones'

urlpatterns = [
    #administrador/instituciones
    url(r'^$', views.inst_lists, name='inst_lists'),

    #administrador/instituciones/3/delete
    url(r'^(?P<pk>[0-9]+)/eliminar/$', views.inst_delete, name='inst_delete'),

    # administrador/instituciones/crear
    url(r'^crear/$', views.inst_create, name='inst_create'),

    # administrador/inst_editar/3
    url(r'^_editar/(?P<pk>[0-9]+)/', views.inst_update.as_view(), name='inst_update')

]

SSInstituciones/urls.py
from django.conf.urls import url

from . import views

app_name = 'Ssinstituciones'

urlpatterns = [
    #administrador/instituciones
    url(r'^$', views.inst_lists, name='inst_lists'),

    #administrador/usuarios/3/delete
    url(r'^/(?P<pk>[0-9]+)/eliminar/$', views.inst_delete, name='inst_delete'),

    # administrador/inst_crear/
    url(r'^_crear/$', views.inst_create, name='inst_create'),

    # administrador/inst_editar/3
    url(r'^_editar/(?P<pk>[0-9]+)/', views.inst_update.as_view(), name='inst_update')

]

Serendipia/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^administrador', include('Index.urls', namespace='administrador')),
    url(r'^admin/', admin.site.urls),
    url(r'^administrador/inst', include('Instituciones.urls', namespace='instituciones')),
    url(r'^administrador/ssinst', include('SSInstituciones.urls', namespace='ssinstituciones')),
]

Instituciones/models.py
from django.db import models

# Create your models here.

class Instituciones(models.Model):
    institucionID = models.IntegerField(
        primary_key = True,
        null = False
    )
    nombre = models.CharField(
        max_length = 50,
        null = False
    )
    direccion = models.CharField(
        max_length = 50,
        null = False
    )
    telefono = models.CharField(
        max_length = 50,
        null = False
    )
    coordenadaX = models.FloatField(
        null = True
    )
    coordenadaY = models.FloatField(
        null = True
    )

    def __str__(self):
        return self.nombre

SSInstituciones/models.py
from django.db import models

# Create your models here.

class SSInstituciones(models.Model):
    institucionID = models.IntegerField(
        primary_key = True,
        null = False
    )
    nombre = models.CharField(
        max_length = 50,
        null = False
    )
    direccion = models.CharField(
        max_length = 50,
        null = False
    )
    telefono = models.CharField(
        max_length = 50,
        null = False
    )
    coordenadaX = models.FloatField(
        null = True
    )
    coordenadaY = models.FloatField(
        null = True
    )

    def __str__(self):
        return self.nombre

Instituciones/forms.py
from .models import Instituciones
from django import forms

class InstForm(forms.ModelForm):
    class Meta:
        model = Instituciones
        fields = ('nombre', 'direccion', 'telefono', 'coordenadaX', 'coordenadaY',)

SSInstituciones/forms.py
from .models import SSInstituciones
from Instituciones.models import Instituciones
from django import forms

class InstForm(forms.ModelForm):
    class Meta:
        model = Instituciones
        fields = ('nombre', 'direccion', 'telefono', 'coordenadaX', 'coordenadaY',)

Instituciones/views.py
from .models import Instituciones
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import UpdateView

from .forms import InstForm


# Create your views here.
def inst_lists(request):
    all_inst = Instituciones.objects.all()
    context ={
        'all_inst': all_inst
        }
    return render(request, 'Instituciones/instituciones_list.html',context)

def inst_delete(request, pk):
    inst = Instituciones.objects.filter(pk=pk)
    inst.delete()
    return HttpResponseRedirect(reverse('Instituciones:inst_lists'))


def inst_create(request):
    context = {}
    NewInstForm = InstForm()

    # if this is a POST request we need to process the form data
    if request.method == 'POST':

        # create a form instance and populate it with data from the request
        NewInstForm = InstForm(request.POST)
        InstValid = NewInstForm.is_valid()

        # check whether it's valid
        if InstValid:
            Inst = NewInstForm.save(commit=False)
            Inst.Activo = True
            ID = Instituciones.objects.count() + 1
            Inst.institucionID = ID
            Inst.save()
            return inst_lists(request)

    context = {
        'NewInstForm': NewInstForm
    }
    return render(request, 'Instituciones/instituciones_form.html', context)

    # if a GET (or any other method) we'll create a blank form
    return render(request, 'Instituciones/instituciones_form.html', context)

class inst_update(UpdateView):
    model = Instituciones
    fields = [
        'nombre',
        'direccion',
        'telefono',
        'coordenadaX',
        'coordenadaY'
    ]
    template_name = 'Instituciones/instituciones_edit_form.html'

    success_url = reverse_lazy('Instituciones:inst_lists')

SSInstituciones/views.py
from .models import SSInstituciones
from Instituciones.models import Instituciones
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import UpdateView

from .forms import InstForm

def inst_lists(request):
    all_inst = Instituciones.objects.all()
    context ={
        'all_inst': all_inst
        }
    return render(request, 'SSInstituciones/instituciones_list.html',context)

def inst_delete(request, pk):
    inst = Instituciones.objects.filter(institucionID=pk)
    inst.delete()
    return HttpResponseRedirect(reverse('Ssinstituciones:inst_lists'))


def inst_create(request):
    context = {}
    NewInstForm = InstForm()

    # if this is a POST request we need to process the form data
    if request.method == 'POST':

        # create a form instance and populate it with data from the request
        NewInstForm = InstForm(request.POST)
        InstValid = NewInstForm.is_valid()

        # check whether it's valid
        if InstValid:
            Inst = NewInstForm.save(commit=False)
            Inst.Activo = True
            ID = Instituciones.objects.count() + 1
            Inst.institucionID = ID
            Inst.save()
            return inst_lists(request)

    context = {
        'NewInstForm': NewInstForm
    }
    return render(request, 'SSInstituciones/instituciones_form.html', context)

    # if a GET (or any other method) we'll create a blank form
    return render(request, 'SSInstituciones/instituciones_form.html', context)



class inst_update(UpdateView):
    model = Instituciones
    fields = [
        'nombre',
        'direccion',
        'telefono',
        'coordenadaX',
        'coordenadaY'
    ]
    template_name = 'SSInstituciones/instituciones_edit_form.html'

    success_url = reverse_lazy('Ssinstituciones:inst_lists')

SSInstituciones/templates/SSInstituciones/instituciones_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container">
    <br>
    <h3 class="center pink-text"> Instituciones - Crear Institución </h3>
    <br> <br> <br>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <div class="row">
                <label for="nombre"> Nombre: </label>
                {{ NewInstForm.nombre | add_class:'form-control' }}
            </div>
            <div class="row">
                <label for="direccion"> Dirección: </label>
                {{ NewInstForm.direccion | add_class:'form-control' }}
            </div>
            <div class="row">
                <label for="telefono"> Teléfono: </label>
                {{ NewInstForm.telefono | add_class:'form-control' }}
            </div>
            <div class="row">
                <label for="coordenadaX"> Latitud: </label>
                {{ NewInstForm.coordenadaX | add_class:'form-control' }}
            </div>
            <div class="row">
                <label for="coordenadaY"> Longitud: </label>
                {{ NewInstForm.coordenadaY | add_class:'form-control' }}
            </div>
        </div>
        <button type="submit" class="waves-light btn pink">Agregar Institución</button>
    </form>
</div>

{% endblock content %}

SSInstituciones/templates/SSInstituciones/instituciones_list.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

    <div class="container">
        <br>
        <h3 class="center pink-text"> Instituciones </h3>
        <br> <br> <br>
        <!--<a href="{% url 'Ssinstituciones:inst_create' %}" class="waves-light btn pink"><i class="material-icons right">add</i>Agregar Instituciones</a>-->
        <br> <br> <br>
        <table class="highlight responsive-table">
            <thead class="thead-default">
                <tr>
                    <th class="center-align">Institución</th>
                    <th class="center-align">Dirección</th>
                    <th class="center-align">Teléfono</th>
                    <th class="center-align">Latitud</th>
                    <th class="center-align">Longitud</th>
                    <!--<th class="center-align">Funcionalidades</th>-->
                </tr>
            </thead>
            <tbody>
            {% for inst in all_inst%}

            <tr>
                <td class="center-align">{{inst.nombre}}</td>
                <td class="center-align">{{inst.direccion}}</td>
                <td class="center-align">{{inst.telefono}}</td>
                <td class="center-align">{{inst.coordenadaX}}</td>
                <td class="center-align">{{inst.coordenadaY}}</td>

                <!--<td class="center-align">
                    <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Editar Usuario"
                        href="{% url 'Ssinstituciones:inst_update' inst.institucionID %}">
                        <i class="material-icons light-blue-text">create</i>
                    </a>&nbsp; &nbsp; &nbsp; &nbsp;
                    <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Eliminar Usuario"
                       href="{% url 'Ssinstituciones:inst_delete' inst.institucionID %}">
                        <i class="material-icons red-text">delete</i>
                    </a> &nbsp; &nbsp; &nbsp; &nbsp;
                </td>-->
            {% endfor %}

            </tbody>
        </table>
    </div>



{% endblock content %}