Estudiantes/urls.py
from django.conf.urls import url

from . import views

app_name = 'Estudiantes'

urlpatterns = [
    #administrador/estudiantes
    url(r'^$', views.student_lists, name='student_lists'),

    # administrador/estudiantes/3/delete
    url(r'^(?P<pk>[0-9]+)/eliminar/$', views.student_delete, name='student_delete'),

    # administrador/estudiantes/3/cambio_status
    url(r'^(?P<pk>[0-9]+)/cambio_status/$', views.student_change_status, name='student_change_status'),

    # administrador/estudiantes/crear/
    url(r'^crear/$', views.student_create, name='student_create'),

    #administrador/estudiantes_editar/3
    url(r'^_editar/(?P<pk>[0-9]+)/', views.student_update.as_view(), name='student_update'),
]

Index/urls.py
from django.conf.urls import url, include
from Usuarios import urls
from . import views

app_name = 'Index'

urlpatterns = [

    #/administrador/
    url(r'^$', views.Index, name='dashboard'),

]

Instituciones/urls.py
from django.conf.urls import url

from . import views

app_name = 'Instituciones'

urlpatterns = [
    #administrador/instituciones
    url(r'^$', views.inst_lists, name='inst_lists'),

    #administrador/instituciones/3/delete
    url(r'^(?P<pk>[0-9]+)/eliminar/$', views.inst_delete, name='inst_delete'),

    # administrador/instituciones/crear
    url(r'^crear/$', views.inst_create, name='inst_create'),

    # administrador/inst_editar/3
    url(r'^_editar/(?P<pk>[0-9]+)/', views.inst_update.as_view(), name='inst_update')

]

Serendipia/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^administrador', include('Index.urls', namespace='administrador')),
    url(r'^admin/', admin.site.urls),
    url(r'^administrador/inst', include('Instituciones.urls', namespace='instituciones')),
    url(r'^administrador/ssinst', include('SSInstituciones.urls', namespace='ssinstituciones')),
]

Usuarios/urls.py
from django.conf.urls import url

from . import views

app_name = 'Usuarios'

urlpatterns = [
    #administrador/usuarios
    url(r'^$', views.user_lists, name='user_lists'),

    #administrador/usuarios/3/delete
    url(r'^(?P<pk>[0-9]+)/eliminar/$', views.user_delete, name='user_delete'),

    #administrador/usuarios/3/cambio_status
    url(r'^(?P<pk>[0-9]+)/cambio_status/$', views.user_change_status, name='user_change_status'),

    #administrador/usuarios_crear/
    url(r'^_crear/$', views.user_create, name='user_create'),

    #administrador/usuarios_editar/3
    url(r'^_editar/(?P<pk>[0-9]+)/', views.user_update.as_view(), name='user_update'),
]

Index/templates/Index/dashboard_admin.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

    <div class="container">
        <img id="AdminMiCuenta" src="{% static "Index/img/Admin/Index_MiCuenta2.png" %}"/>
        <a href="{% url 'Estudiantes:student_lists' %}"><img id="AdminEstudiante" src="{% static "Index/img/Admin/Index_Estudiantes2.png" %}"/> </a>
        <img id="AdminAsistencias" src="{% static "Index/img/Admin/Index_Asistencias2.png" %}"/>
        <img id="AdminClases" src="{% static "Index/img/Admin/Index_Clases2.png" %}"/>
        <a href="{% url 'Instituciones:inst_lists' %}"><img id="AdminInstituciones" src="{% static "Index/img/Admin/Index_Instituciones2.png" %}"/></a>
        <img id="AdminReportes" src="{% static "Index/img/Admin/Index_Reportes2.png" %}"/>
        <a href="{% url 'Usuarios:user_lists' %}"><img id="AdminUsuarios" src="{% static "Index/img/Admin/Index_Usuarios2.png" %}"/> </a>
    </div>

{% endblock content %}

Index/templates/Index/login.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Serendipia - Iniciar Sesion</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!--Import CSS (Materialize, Freelancer)-->
    <link type="text/css" href="{% static "Index/css/materialize.min.css" %}" rel="stylesheet" media="screen,projection">
    <link type="text/css" href="{% static "Index/css/freelancer.css" %}" rel="stylesheet" media="screen,projection">

</head>

<body>
    <div class="container">
        <br> <br> <br> <br> <br> <br>
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="input-field col s4 offset-s4">
                    <label for="Email">Email</label>
                    {{ NewLoginForm.Email | add_class:'form-control' }}
                </div>
            </div>
            <div class="row">
                <div class="input-field col s4 offset-s4">
                    <label for="Password">Contrasenia</label>
                    {{ NewLoginForm.Passwd | add_class:'form-control' }}
                </div>
            </div>
            <button type="submit" class="waves-light btn green accent-2">Iniciar Sesion</button>
        </form>
    </div>
</body>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="{% static "Index/js/materialize.min.js" %}"></script>

</html>