Index/urls.py
from django.conf.urls import url, include
from Usuarios import urls
from . import views

app_name = 'Index'

urlpatterns = [

    #/administrador/
    url(r'^$', views.Index, name='dashboard'),

]

Serendipia/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^administrador', include('Index.urls', namespace='administrador')),
    url(r'^admin/', admin.site.urls),
    url(r'^administrador/inst', include('Instituciones.urls', namespace='instituciones')),
    url(r'^administrador/ssinst', include('SSInstituciones.urls', namespace='ssinstituciones')),
]

Usuarios/urls.py
from django.conf.urls import url

from . import views

app_name = 'Usuarios'

urlpatterns = [
    #administrador/usuarios
    url(r'^$', views.user_lists, name='user_lists'),

    #administrador/usuarios/3/delete
    url(r'^(?P<pk>[0-9]+)/eliminar/$', views.user_delete, name='user_delete'),

    #administrador/usuarios/3/cambio_status
    url(r'^(?P<pk>[0-9]+)/cambio_status/$', views.user_change_status, name='user_change_status'),

    #administrador/usuarios_crear/
    url(r'^_crear/$', views.user_create, name='user_create'),

    #administrador/usuarios_editar/3
    url(r'^_editar/(?P<pk>[0-9]+)/', views.user_update.as_view(), name='user_update'),
]

Usuarios/models.py
from django.db import models

# Create your models here.

class Usuarios(models.Model):

    Usuarioid = models.IntegerField(
        primary_key=True,
        null=False,
    )

    Nombre = models.CharField(
        max_length=50,
        null=False
    )

    Apaterno = models.CharField(
        max_length=50,
        null=False
    )

    Amaterno = models.CharField(
        max_length=50,
        null=False
    )

    Telefono = models.CharField(
        max_length=15,
    )

    Email = models.EmailField(
        null=False
    )

    Passwd = models.CharField(
        max_length=20,
        null=False
    )

    Activo = models.BooleanField(
        default=True
    )

    def __str__(self):
        return self.Nombre + ' ' + self.Apaterno + ' ' + self.Amaterno

Usuarios/forms.py
from .models import Usuarios
from django import forms

class UsuariosForm(forms.ModelForm):
    class Meta:
        model = Usuarios
        fields = ('Nombre', 'Apaterno', 'Amaterno', 'Telefono', 'Email', 'Passwd')

class LoginForm(forms.ModelForm):
    class Meta:
        model = Usuarios
        Passwd = forms.CharField(widget=forms.PasswordInput)
        fields = ('Email', 'Passwd')

Usuarios/views.py
from django.shortcuts import render
from django.views.generic import UpdateView
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse, reverse_lazy

from .models import Usuarios

from .forms import UsuariosForm, LoginForm

# Create your views here.

def login(request):
    context = {}
    NewLoginForm = LoginForm()
    #Checar POST
    if request.method == 'POST':
        NewLoginForm = LoginForm(request.POST)
        UserValid = NewLoginForm.is_valid()
        #Checar que la forma sea valida
        if UserValid:
            Usu = NewLoginForm.save(commit=False)
            #Checar que el usuario sea Administrador
            emailValid = Usuarios.objects.filter(Email=Usu.Email, Passwd=Usu.Passwd)
            #Checar que el usuario y la contrasenia esten en la BD
            if emailValid.count() > 0:
                return render(request, 'Index/dashboard_admin.html', context)

        context = {
            'NewLoginForm': NewLoginForm
        }
        return render(request, 'Index/login.html', context)

    context = {
        'NewLoginForm': NewLoginForm
    }
    return render(request, 'Index/login.html', context)

    # context = {}
    # if request == 'POST':
    #     email = request.POST['Email']
    #     password = request.POST.get('Password')
    #     user = Usuarios.objects.filter(Email=email)
    #     if user.count() > 0:
    #         return render(request, 'Index/dashboard_admin.html', context)
    # return render(request, 'Index/login.html', context)

    # email = request.POST.get('Email', False)
    # password = request.POST.get('Password', False)
    # user = Usuarios.objects.filter(Email=email)
    # if user.count() > 0:
    #     user = Usuarios.objects.filter(Email=email, Passwd=password)
    #     if user.count() > 0:
    #         context ={}
    #         return render(request, 'Index/login.html',context)
    #     else:
    #         return HttpResponseRedirect(reversed('Index/login.html'))
    # else:
    #     return HttpResponseRedirect(reversed('Index/login.html'))


def user_lists(request):
    all_users = Usuarios.objects.all()
    context ={
        'all_users': all_users
        }
    return render(request, 'Usuarios/usuarios_list.html',context)


def user_create(request):
    context = {}
    NewUsuariosForm = UsuariosForm()

    # if this is a POST request we need to process the form data
    if request.method == 'POST':

        # create a form instance and populate it with data from the request
        NewUsuariosForm = UsuariosForm(request.POST)
        UserValid = NewUsuariosForm.is_valid()

        # check whether it's valid
        if UserValid:
            Usu = NewUsuariosForm.save(commit=False)
            Usu.Activo = True
            ID = Usuarios.objects.count() + 1
            Usu.Usuarioid = ID
            Usu.save()
            return user_lists(request)

    context = {
        'NewUsuariosForm': NewUsuariosForm
    }
    return render(request, 'Usuarios/usuarios_form.html', context)

    # if a GET (or any other method) we'll create a blank form
    return render(request, 'Usuarios/usuarios_form.html', context)

class user_update(UpdateView):
    model = Usuarios
    fields = [
        'Nombre',
        'Apaterno',
        'Amaterno',
        'Telefono',
        'Email',
        'Passwd'
    ]
    template_name = 'Usuarios/user_edit_form.html'

    success_url = reverse_lazy('Usuarios:user_lists')

def user_delete(request, pk):
    user = Usuarios.objects.filter(pk=pk)
    user.delete()
    return HttpResponseRedirect(reverse('Usuarios:user_lists'))

def user_change_status(request, pk):
    user = Usuarios.objects.get(pk=pk)
    if user.Activo:
        user.Activo = False
        user.save()
    else:
        user.Activo = True
        user.save()
    return HttpResponseRedirect(reverse('Usuarios:user_lists'))

Usuarios/templates/Usuarios/user_edit_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container">
    <br>
    <h3 class="center green-text text-accent-2"> Usuarios - Crear Usuario </h3>
    <br> <br> <br>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <button type="submit" class="waves-light btn green accent-2">Confimar Usuario</button>
    </form>
</div>

{% endblock content %}

Usuarios/templates/Usuarios/usuarios_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container">
    <br>
    <h3 class="center green-text text-accent-2"> Usuarios - Crear Usuario </h3>
    <br> <br> <br>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <div class="row">
                <label for="Nombre"> Nombre: </label>
                {{ NewUsuariosForm.Nombre | add_class:'form-control' }}
            </div>
            <div class="row">
                <label for="Apaterno"> Apellido Paterno: </label>
                {{ NewUsuariosForm.Apaterno | add_class:'form-control' }}
            </div>
            <div class="row">
                <label for="Amaterno"> Apellido Materno: </label>
                {{ NewUsuariosForm.Amaterno | add_class:'form-control' }}
            </div>
            <div class="row">
                <label for="Telefono"> Telefono: </label>
                {{ NewUsuariosForm.Telefono | add_class:'form-control' }}
            </div>
            <div class="row">
                <label for="Email"> Email: </label>
                {{ NewUsuariosForm.Email | add_class:'form-control' }}
            </div>
            <div class="row">
                <label for="Passwd"> Contrasenia: </label>
                {{ NewUsuariosForm.Passwd | add_class:'form-control' }}
            </div>
        </div>
        <button type="submit" class="waves-light btn green accent-2">Agregar Usuario</button>
    </form>
</div>

{% endblock content %}

Usuarios/templates/Usuarios/usuarios_list.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

    <div class="container">
        <br>
        <h3 class="center green-text text-accent-2"> Usuarios </h3>
        <br> <br> <br>
        <a href="{% url 'Usuarios:user_create' %}" class="waves-light btn green accent-2"><i class="material-icons right">add</i>Agregar Usuario</a>
        <br> <br> <br> <br>
        <table class="highlight responsive-table">
            <thead class="thead-default">
                <tr>
                    <th class="center-align">Nombre</th>
                    <th class="center-align">Apellidos</th>
                    <th class="center-align">Telefono</th>
                    <th class="center-align">Email</th>
                    <th class="center-align">Funcionalidades</th>
                    <th class="center-align">Activo</th>
                </tr>
            </thead>
            <tbody>
            {% for user in all_users %}

            <tr>
                <td class="center-align">{{user.Nombre}}</td>
                <td class="center-align">{{user.Apaterno}} {{user.Amaterno}}</td>
                <td class="center-align">{{user.Telefono}}</td>
                <td class="center-align">{{user.Email}}</td>

                <td class="center-align">
                    <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Editar Usuario"
                       href="{% url 'Usuarios:user_update' user.pk %}">
                        <i class="material-icons light-blue-text">create</i>
                    </a>&nbsp; &nbsp; &nbsp; &nbsp;
                    <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Eliminar Usuario"
                       href="{% url 'Usuarios:user_delete' user.pk %}">
                        <i class="material-icons red-text">delete</i>
                    </a> &nbsp; &nbsp; &nbsp; &nbsp;
                    <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Cambiar Estatus"
                       href="{% url 'Usuarios:user_change_status' user.pk %}">
                    <i class="material-icons blue-grey-text">compare_arrows</i>
                    </a>
                </td>

                {% if user.Activo == True %}
                <td class="center-align"><i class="material-icons green-text">done</i></td>
                {% else %}
                <td class="center-align"><i class="material-icons red-text">clear</i></td>
                {% endif %}
            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>



{% endblock content %}